#broker installation
- hosts: broker
  become: yes
  become_user: root
  become_method: sudo
    
  tasks:

  - name: Instalar la llave pública de RabbitMQ
    apt_key:
      url: https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc
      state: present
      
  - name: Agregar repositorio oficial de RabbitMQ
    apt_repository:
      repo: deb https://dl.bintray.com/rabbitmq/debian bionic main
      state: present
      filename: rabbitmq

  - name: Instalar la llave pública de Erlang
    apt_key:
      url: http://binaries.erlang-solutions.com/debian/erlang_solutions.asc
      state: present
 
  - name: Agregar repositorio oficial de Erlang
    apt_repository:
      repo: deb http://binaries.erlang-solutions.com/debian bionic contrib
      state: present
      filename: erlang
      
  - name: Instalar Rabbitmq
    apt:
      name: "{{ item }}"
      update_cache: yes
      install_recommends: yes
      state: present
    with_items:
      - rabbitmq-server   
  
  - name: Start the RabbitMQ server
    service:
    name: rabbitmq-server
    state: started

  - name: Start management UI
    command: /usr/lib/rabbitmq/bin/rabbitmq-plugins enable rabbitmq_management
  
  - name: Enabled RabbitMQ plugins
    rabbitmq_plugin:
      names: rabbitmq_management
      state: enabled

  - name: Add RabbitMQ Deploy user
    rabbitmq_user:
      user: deploy
      password: password
      tags: administrator, deploy
      vhost: /
      configure_priv: .*
      read_priv: .*
      write_priv: .*
      state: present

  - name: Remove default user
    rabbitmq_user:
      user: guest
      state: absent

  - name: Restart RabbitMQ server
    service:
      name: rabbitmq-server
      state: restarted

# consumidorA installation
- hosts: consumidorA
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
 
  tasks:

    - name: install pip
      apt:
        name: python-pip
        state: present
        
    - name: install pika
      pip: 
        name: pika
    
    - name: install git
      apt:
        name: git
        state: present
    
    - name: python archives | clone repo
      git:
        repo: https://github.com/dvlopez9811/Rabbitmqtest.git
        dest: /src
        accept_hostkey: no
      register: git_finished

    - name: Give permissions python script A
      when: git_finished.changed
      file:
        path: /src/Parcial1_Quintero-Varela/src/consumidorA.py
        owner: root
        group: root
        mode: '777'

# consumidorB installation
- hosts: consumidorB
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: install pip
      apt:
        name: python-pip
        state: present
        
    - name: install pika
      pip: 
        name: pika
    
    - name: install git
      apt:
        name: git
        state: present
    
    - name: python archives | clone repo
      git:
        repo: https://github.com/dvlopez9811/Rabbitmqtest.git
        dest: /src
        accept_hostkey: no
      register: git_finished

    - name: Give permissions python script B
      when: git_finished.changed
      file:
        path: /src/Parcial1_Quintero-Varela/src/consumidorB.py
        owner: root
        group: root
        mode: '777'

# productor installation
- hosts: productor
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: install pip
      apt:
        name: python-pip
        state: present
        
    - name: install pika
      pip: 
        name: pika
    
    - name: install git
      apt:
        name: git
        state: present
    
    - name: python archives | clone repo
      git:
        repo: https://github.com/dvlopez9811/Rabbitmqtest.git
        dest: /src
        accept_hostkey: no
      register: git_finished
